parameters:
  path: trovaprezzifeed

trovaprezzifeed_settings:
  resource: 'routes/settings.yml'
  prefix: /trovaprezzifeed

trovaprezzifeed_category_blacklist:
  resource: 'routes/category_blacklist.yml'
  prefix: /trovaprezzifeed

trovaprezzifeed_product_blacklist:
  resource: 'routes/product_blacklist.yml'
  prefix: /trovaprezzifeed

trovaprezzifeed_supplier_blacklist:
  resource: 'routes/supplier_blacklist.yml'
  prefix: /trovaprezzifeed
